### PR TITLE
MVP Data Model

### PR DESCRIPTION
**Pull request by AughdonBreslin**
Sup gamers, this can now take in a list of materials and a total weight and calculate the total carbon output and price to offset it!

### CODE REVIEW

**Review by ceiphr — APPROVED** [review]
LGTM. Fix merge conflict though @chaaf3.

**Comment by AughdonBreslin** [comment]
Resolved merge conflicts

**Review by chaaf3 — APPROVED** [review]

**Comment by chaaf3** [comment]
You already fixed the conflict which was my only issue!

**Comment by ceiphr** [comment]
LGTM, merging.

**Pull request merged**
